import * as path from "jsr:@std/path";
import * as nodePath from "node:path"

export function securePath(baseDir: string, userPath: string): string | null {
  /* Generated by Emeri-Sonn-4*/
  // sanitize first
  const clean = userPath.replace(/\.\./g, '');
  
  // join and normalize
  const fullPath = path.normalize(path.join(baseDir, clean));
  
  // make sure we're still in the base directory
  if (!fullPath.startsWith(path.normalize(baseDir) + nodePath.sep)) {
    return null; // nice try asshole
  }
  
  return fullPath;
}
